# -*- coding: utf-8 -*-
"""KNN(sklearn).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12IbJQpmZCNW8o7RQxGMzKN2X6i4MNt94
"""

from sklearn.neighbors import KNeighborsClassifier
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

iris = datasets.load_iris()
X = iris.data
y = iris.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

knn = KNeighborsClassifier(n_neighbors = 100)
knn.fit(X_train, y_train)

predictions = knn.predict(X_test)

accuracy = accuracy_score(y_test, predictions)
print("Accuracy:", accuracy * 100)