# -*- coding: utf-8 -*-
"""AbdullahBinAltaf-Lab11(TASK1)-17May2024.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QVB_EUkusrJrFiAz1A7xjcfxardsGszr
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
# %matplotlib inline

df = pd.read_csv('height-weight.csv')

df.head()

plt.scatter(df['Weight'], df['Height'])
plt.xlabel("Weight")
plt.ylabel("Height")

df.corr()

X = df[['Weight']]
y = df['Height']

X_series = df['Weight']
np.array(X_series).shape

np.array(y).shape

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 42)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)

X_test

scaler = StandardScaler()
X_test = scaler.fit_transform(X_test)

X_test

from sklearn.linear_model import LinearRegression

regression = LinearRegression(n_jobs = -1)

regression.fit(X_train, y_train)

print("Coefficient or Slope:", regression.coef_)
print("Intercept:", regression.intercept_)

plt.scatter(X_train, y_train)
plt.plot(X_train, regression.predict(X_train))

y_pred = regression.predict(X_test)

from sklearn.metrics import mean_absolute_error, mean_squared_error

mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mse)
print(mse)
print(mae)
print(rmse)