# -*- coding: utf-8 -*-
"""AbdullahBinAltaf-Lab08-AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XLInCxre9KYLmXyMpIttCbNE8FATAGbf
"""

import numpy as np
import pandas as pd

df = pd.read_csv('data.csv')
df.head()

df.drop(columns=['id', 'Unnamed: 32'], inplace = True)
df.head()

df.shape

X = df.drop('diagnosis', axis = 1)
y = df['diagnosis']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 2)

y_train.head()

X_train.shape

X_train.head()

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

X_train

X_train.shape

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 1)

knn.fit(X_train, y_train)

from sklearn.metrics import accuracy_score
y_pred = knn.predict(X_test)
accuracy_score(y_test, y_pred)

scores = []
for i in range (1, 16):
  knn = KNeighborsClassifier(n_neighbors = 1)
  knn.fit(X_train, y_train)
  y_pred = knn.predict(X_test)
  scores.append(accuracy_score(y_test, y_pred))

scores

import matplotlib.pyplot as plt
plt.plot(range(1, 16), scores)